spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.131/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.2.131
    port: 6379

#logging:
#  pattern:
#    console: "%d -%msg%n"
##  path: ./var/log/tomcat/
#  file: ./var/log/tomcat/sell.log
#  level:
server:
  context-path: /sell
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wx83549c2cbd9c0cc7
#  mpAppId: wxd898fcb01713c658
  mpAppSecret: f732444338adcea37f7062888080a364
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/eric/h5.p12
  notifyUrl: http://lili.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: SSDdoyFlaTklt-M4kro4iKSRPZlBA3l644LFiODYYgc

projectUrl:
  wechatMpAuthorize: http://lili.natapp1.cc
  wechatOpenAuthorize: http://lili.natapp1.cc
  sell: http://lili.natapp1.cc

logging:
  level:
    com.imooc.dataobject.mapper: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
